platform :ios, '8.0'
inhibit_all_warnings!
target 'hinabian' do
#    pod 'AFNetworking', '~> 3.1.0'
#    pod 'SDWebImage', '~> 4.0.0'
#    pod 'NJKWebViewProgress', '~> 0.2.3'
#    pod 'Base64nl', '~> 1.2'
#    pod 'MagicalRecord', '~> 2.3.2'
#    pod 'YYText', '~> 1.0.2'
#    pod 'YYImage', '~> 1.0.4'
#    pod 'YYCache', '~> 1.0.4'
#    pod 'MJExtension', '~> 3.0.12'
#    pod 'MBProgressHUD', '~> 1.0.0'
#    pod 'SDAutoLayout', '~> 2.1.7'
#    pod 'SDCycleScrollView','~> 1.73'
#    pod 'Meiqia', '~> 3.4.5'
#    pod 'MJRefresh'
#    pod 'Fabric'
#    pod 'Crashlytics'
#    pod 'NIMKit'
#    pod 'Reachability', '~> 3.2'

# UMSocial ---6.4.6 (建议微信与TencentAPI 版本由我们控制，因此使用精简版)
# 集成新浪微博(完整版25.3M) pod 'UMengUShare/Social/Sina'
# 集成QQ/QZone/TIM(完整版7.6M) pod 'UMengUShare/Social/QQ'
# 集成微信(完整版14.4M) pod 'UMengUShare/Social/WeChat'

# U-Share SDK UI模块
#    pod 'UMengUShare/UI'
# 集成微信(精简版0.2M)
#    pod 'UMengUShare/Social/ReducedWeChat'
# 集成QQ/QZone/TIM(精简版0.5M)
#    pod 'UMengUShare/Social/ReducedQQ'
# 集成新浪微博(精简版1M)
#    pod 'UMengUShare/Social/ReducedSina'

end
